CREATE DATABASE PRODUCT_DETAILS;
USE PRODUCT_DETAILS;

CREATE TABLE PRODUCTS
(
    PRODUCT_ID INT NOT NULL,
    PRODUCT_COST INT (5),
    PRODUCT_RETAIL INT (5),
    PRODUCT_NAME VARCHAR(50),
    STORE_ID INT NOT NULL,
    TODAY INT,

    CONSTRAINT PRODUCT_PRIMKEY PRIMARY KEY (PRODUCT_ID)
);