CREATE DATABASE STORE_SALES;
USE STORE_SALES;
CREATE TABLE  CANVAS_STORE
   (
	EMP_ID INT NOT NULL UNIQUE,
	EMPLOYEE VARCHAR(50), 
	CASH INT NOT NULL, 
	CARD INT NOT NULL, 
	TOTAL INT NOT NULL, 
	EXPENSES INT NOT NULL
    
);

