select max(total), EMPLOYEE from CANVAS_STORE
where employee = 'SAM';

SELECT SUM(CASH) AS CASH, AVG(CASH) AS AVERAGE, MAX(CASH) AS MAX, MIN(CASH) AS MIN, COUNT(*)
FROM CANVAS_STORE;

SELECT AVG(TOTAL) AS AVERAGE_SALE, EMPLOYEE
FROM CANVAS_STORE
GROUP BY EMPLOYEE
HAVING AVG(TOTAL) > 650;